# Generated by Django 5.0.1 on 2024-02-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airline",
            name="boarding_deplaining_rating",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="airline",
            name="crew_rating",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="airline",
            name="entertainment_rating",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="airline",
            name="services_rating",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="airline",
            name="wi_fi_rating",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
