# Generated by Django 5.0.1 on 2024-01-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="airport",
            name="timezone",
            field=models.CharField(default="UTC", max_length=63),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="airline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="airplanes",
                to="airport_system.airlines",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("flight", "row", "seat"),
                name="validate_unique",
                violation_error_message="Internal Server Error",
            ),
        ),
    ]
