# Generated by Django 5.0.1 on 2024-02-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0003_remove_airline_overall_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airline",
            name="boarding_deplaining_rating",
        ),
        migrations.RemoveField(
            model_name="airline",
            name="crew_rating",
        ),
        migrations.RemoveField(
            model_name="airline",
            name="entertainment_rating",
        ),
        migrations.RemoveField(
            model_name="airline",
            name="services_rating",
        ),
        migrations.RemoveField(
            model_name="airline",
            name="wi_fi_rating",
        ),
        migrations.RemoveField(
            model_name="airlinerating",
            name="category",
        ),
        migrations.RemoveField(
            model_name="airlinerating",
            name="rating",
        ),
        migrations.AddField(
            model_name="airlinerating",
            name="boarding_deplaining_rating",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=0,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="airlinerating",
            name="crew_rating",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=0,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="airlinerating",
            name="entertainment_rating",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=0,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="airlinerating",
            name="services_rating",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=0,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="airlinerating",
            name="wi_fi_rating",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=0,
                null=True,
            ),
        ),
    ]
