# Generated by Django 5.0.1 on 2024-02-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0004_remove_airline_boarding_deplaining_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airline",
            name="headquarter",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Headquarter"
            ),
        ),
        migrations.AlterField(
            model_name="airline",
            name="iata_icao",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="IATA/ICAO Codes"
            ),
        ),
        migrations.AlterField(
            model_name="airline",
            name="web_site_address",
            field=models.URLField(
                blank=True, null=True, verbose_name="Web-site Address"
            ),
        ),
    ]
