# Generated by Django 5.0.1 on 2024-01-20 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0004_alter_airport_timezone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="emergent_airport",
            new_name="airport",
        ),
        migrations.RenameField(
            model_name="flight",
            old_name="estimated_arrival_time",
            new_name="arrival_time",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="planned_airport",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="real_arrival_time",
        ),
    ]
