# Generated by Django 5.0.1 on 2024-01-25 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0005_rename_emergent_airport_flight_airport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.IntegerField()),
                ("seat_number", models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="ticket",
            name="validate_unique",
        ),
        migrations.RemoveField(
            model_name="airplane",
            name="rows",
        ),
        migrations.RemoveField(
            model_name="airplane",
            name="seats_in_row",
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "flight"), name="unique_row_seat_flight"
            ),
        ),
        migrations.AddField(
            model_name="seat",
            name="airplane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="airport_system.airplane",
            ),
        ),
    ]
