# Generated by Django 5.0.1 on 2024-02-23 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0006_crew_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="distance",
        ),
    ]
