# Generated by Django 5.0.1 on 2024-01-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0007_ticket_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="allocated",
            field=models.BooleanField(default=True),
        ),
    ]
