# Generated by Django 5.0.1 on 2024-02-23 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0007_remove_route_distance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="airport",
            new_name="standard_airport",
        ),
    ]
