# Generated by Django 5.0.1 on 2024-02-23 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0008_rename_airport_flight_standard_airport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="standard_airport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standard_flights",
                to="airport_system.airport",
            ),
        ),
    ]
