# Generated by Django 5.0.1 on 2024-03-01 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0010_flight_emergent_airport"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="emergent_destination",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emergent_destination_routes",
                to="airport_system.airport",
            ),
            preserve_default=False,
        ),
    ]
