# Generated by Django 5.0.1 on 2024-03-01 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0011_route_emergent_destination"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="destination",
            new_name="standard_destination",
        ),
    ]
