# Generated by Django 5.0.1 on 2024-03-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0014_alter_route_emergent_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="status",
            field=models.CharField(
                choices=[("on schedule", "On schedule"), ("emergency", "Emergency")],
                default="emergency",
                max_length=20,
            ),
        ),
    ]
