# Generated by Django 5.0.1 on 2024-03-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0015_route_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="status",
            field=models.CharField(
                choices=[("on schedule", "On schedule"), ("emergency", "Emergency")],
                default="on schedule",
                max_length=20,
            ),
        ),
    ]
