# Generated by Django 5.0.1 on 2024-03-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport_system", "0017_rename_crews_flight_crew"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="distance",
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
